[package]
name = "tests"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
publish = false

[dev-dependencies]
citationberg = { workspace = true, features = ["json"] }
hayagriva-archive = { workspace = true }
hayagriva-core = { workspace = true }
hayagriva-csl = { workspace = true }
hayagriva-format = { workspace = true, features = ["biblatex"] }
hayagriva-json = { workspace = true }
serde_json = "1"
regex = "1"
unscanny = { workspace = true }

[[test]]
name = "citeproc"
path = "tests/citeproc.rs"
